name: Angular_DockerImage

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  angular_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: npm install
        run: npm install

      - name: build
        run: |
           npm run build -- --output-path=docs
                 
      - name: list
        run:
           ls -la docs
      
      - name: list browser
        run: |
           ls -la docs/browser

       # LOGIN A DOCKER HUB
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
       
        # DESCARGAR Y EJECUTAR IMAGEN BASE
      - name: Download and run the Docker base image
        run: |
          docker run -d --name http_base httpd
     
          docker exec http_base sh -c "
            echo '
            LoadModule rewrite_module modules/mod_rewrite.so

            <Directory \"/usr/local/apache2/htdocs\">
                AllowOverride All
                Require all granted
            </Directory>
            ' >> /usr/local/apache2/conf/httpd.conf
            "

      # COPIAR APP ANGULAR AL CONTENEDOR
      - name: copy model to the Docker image
        run: |
          docker cp docs/browser/. http_base:/usr/local/apache2/htdocs
          docker cp src/.htaccess http_base:/usr/local/apache2/htdocs/.htaccess
      # CREAR IMAGEN PERSONALIZADA
      - name: Build the custom Docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          docker commit --change "ENV MODEL_NAME http_base" http_base $DOCKER_USER/lifegoals:latest

      # HACER PUSH A DOCKER HUB
      - name: Docker Push
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          docker push $DOCKER_USER/lifegoals:latest


      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
